From c59f055141ae8b1cec801f294a399639195241fd Mon Sep 17 00:00:00 2001
From: Michel Alexandre Salim <salimma@fedoraproject.org>
Date: Thu, 14 Jul 2011 12:36:44 +0200
Subject: [PATCH] import_itunes_path should catch the ValueError exception
 thrown when the path does not exist

---
 tv/lib/importmedia.py |    2 +-
 1 files changed, 1 insertions(+), 1 deletions(-)

diff --git a/tv/lib/importmedia.py b/tv/lib/importmedia.py
index c525bfc..45b950c 100644
--- a/tv/lib/importmedia.py
+++ b/tv/lib/importmedia.py
@@ -102,5 +102,5 @@ def import_itunes_path(path):
         parser.parse(os.path.join(path, ITUNES_XML_FILE))
         music_path = file_path_xlat(handler.music_path)
         return music_path
-    except (IOError, xml.sax.SAXParseException):
+    except (IOError, xml.sax.SAXParseException, ValueError):
         pass
-- 
1.7.6

